### ISSUE TITLE
BaseColorFactor material is not exported

### ISSUE THREAD

**Issue by thoced** [KhronosGroup/glTF-Blender-Exporter#140] opened 2017-12-29 15:39 UTC
Hello

The name of the texture and the texture associated with the BaseColorFactor is exported but not the name and the index in the list of materials, is this normal?

Thank you

example :

```
"images" : [
       {
           "uri" : "TexturesCom_WornWood2_1024_albedo.png"
       }, 
       {
           "uri" : "LightMapAtlasHouse.png"    <--  OK the texture is exported
       }
   ], 

"materials" : [
       {
           "name" : "Material", 
           "pbrMetallicRoughness" : {
               "baseColorTexture" : {
                   "index" : 0
               }
               <--  MISSING "baseColorFactor" ??
           }
       }
   ], 

```

**Comment by emackey** [comment] 2017-12-29 18:21
Duplicate of #98.

The BaseColorFactor is a solid color, not a texture, and must be directly set on the node.  For a texture just use the BaseColor node input.

**Closed by emackey** 2017-12-29 18:21 UTC
