### ISSUE TITLE
Animation issue with simple armature

### ISSUE THREAD

**Issue by tkazik** [KhronosGroup/glTF-Blender-Exporter#115] opened 2017-11-18 10:47 UTC
Hi folks

I am encountering an issue when trying to export a very basic armature animation. Somehow the rotation axis gets twisted. Am I missing a very basic convention?

![gltf_armature_animation](https://user-images.githubusercontent.com/15689124/32979417-3d571f50-cc55-11e7-9482-97abbef711b6.png)

Here is the blend file and also the gltf files, where one file is generated using this exporter (animation visible, but wrong axis/location as shown above) and the other using [kupoman's exporter](https://github.com/Kupoman/blendergltf) (no animation visible at all):

[simple_armature_animation.zip](https://github.com/KhronosGroup/glTF-Blender-Exporter/files/1484500/simple_armature_animation.zip)

Thank you very much for your feedback

**Comment by UX3D-nopper** [comment] 2017-11-18 10:56
Hi, the problem is, that the cube mesh vertices/primitives are not assigned to the bone.
Please assign the vertices to a bone/joint and then the export should work.

**Closed by UX3D-nopper** 2017-11-18 10:56 UTC
Labels: enhancement, wontfix

**Comment by tkazik** [comment] 2017-11-19 11:38
Thanks for the quick reply. The cube is in fact parented to the bone. This looks alright in blender...why isn't that enough for the export?
Your suggestion works, if I parent the cube to the bone with 'armature deform -> with automatic weights'. But isn't that kind of an overkill, as my intention is not to deform anything.

Furthermore, I applied your suggestion to a bit more complicated model and the viewers throw lots of errors, see attachment. Any hints and tips on what I am missing are greatly appreciated!

[b737_gear_animation.zip](https://github.com/KhronosGroup/glTF-Blender-Exporter/files/1485502/b737_gear_animation.zip)
