### ISSUE TITLE
Support splitting primitives according to max number of uniforms

### ISSUE THREAD

**Issue by ale64bit** [KhronosGroup/glTF-Blender-Exporter#167] opened 2018-03-03 16:42 UTC
It would be quite useful to (optionally) split the exported primitives so that the number of bones affecting each primitive doesn't exceed a certain number that users can setup when exporting. This would simplify writing certain shaders and loading assets specifically for games/game engines.

**Comment by donmccurdy** [comment] 2018-03-07 01:23
Would it be sufficient to let each vertex group in Blender be exported as separate primitives? Detecting reasonable ways to automatically split the mesh in this way sounds pretty complicated for an exporter to be doing...

**Comment by motorsep** [comment] 2018-03-07 01:32
I think it would be a good compromise. Worth noting that if target software (a game engine for example) doesn't support such thing, then it would make no difference.

**Comment by ale64bit** [comment] 2018-03-07 12:40
My knowledge about this is pretty limited, so please do whatever you consider more sensible. My motivation is that when writing shaders involving skinning for games, the need for joint matrix calculation and passing as uniform, limits the number of those you can actually use per draw call (I have seen a maximum of 12, meaning a maximum of 4 bones affecting any vertex). Since normally the original assets are converted to some engine-specific format this problem is solved by splitting the original mesh when necessary (e.g. libgdx's fbx-conv tool will split the mesh if needed). I thought that if GLTF aims to be a minimal-effort runtime-ready format, having such option in the exporter itself would makes sense.

If this is actually easy to automate from Blender by the artist itself then I'm fine with having each vertex group be a separate primitive.

**Comment by motorsep** [comment] 2018-03-07 16:12
75 bones is a limit for GPU skinning on mobile agaik. 255 on desktop. 1-8 vertices per bone. That's quite plenty enough. Just look at gorgeous Paragon (UE4) character models. I am pretty sure there is no proctical need to split mesh into several meshes nowadays.

**Comment by shakesoda** [comment] 2018-03-07 16:28
No, this is very much still a real need. I don't believe the exporter can
make any kind of informed decision about this though, every engine and
api/hardware target has a different limit.

If the exporter went and did something incredibly conservative like split
every (non-overlapping) group into a separate primitive, you just have to
fix it again on import anyway, which leaves everyone at square one (or
worse, since now existing implementations get to deal with combining these
messy files instead of just splitting them). Alternatively, you end up with
configurable limits that... still cause engines to need code for
splitting/merging. Because of this, I think this work belongs in the
importer, not the exporter.


- Colby

**Comment by donmccurdy** [comment] 2018-03-07 16:42
Yeah, I guess we're talking about two limits here:

1. limit of 75-255 bones, total
    * I don't think we can automatically fix this in the exporter, but allowing vertex groups to be exported as separate primitives might help.
2. limit of 4-8 joint influences per vertex
    * the exporter can't really do anything useful if you assign too many joints to a vertex, but Blender gives [tools to limit this during weight painting](https://blender.stackexchange.com/questions/14250/how-to-restrict-vertex-weights-to-no-more-than-n-number-of-bones).

**Comment by ale64bit** [comment] 2018-03-07 16:42
Well, one of the reasons I quite liked GLTF is that actually you don't need much of an "importer" since the format is very suited for real-time rendering. The informed decision in this case would probably boil down to split the primitives such that any output primitive is not affected by more than some user-configurable limit (defaulting to infinity, meaning no split).

**Comment by lexaknyazev** [comment] 2018-03-07 16:47
@donmccurdy 
> limit of 4-8 joint influences per vertex

It would be nice to have an issue tracking 8 influences support across ecosystem.

**Comment by donmccurdy** [comment] 2018-03-07 16:54
> Well, one of the reasons I quite liked GLTF is that actually you don't need much of an "importer" since the format is very suited for real-time rendering. 

If you can't do processing after import (this is my situation as well, working with three.js) then I think it's necessary to fix things in Blender before export. Splitting the mesh won't help with the 4-8 bones per vertex limit. And while the limit on total bones could be fixed by splitting, there's no perfect strategy guaranteed to work without changing the result, to me it feels like something an artist can do better. For example, you might want to isolate a character's face from the body.

> It would be nice to have an issue tracking 8 influences support across ecosystem.

Good point. Some historical discussion: https://github.com/mrdoob/three.js/issues/12127

**Comment by shakesoda** [comment] 2018-03-07 17:17
@donmccurdy for the case of >4 weights/vertex, the exporter could chop off everything but largest 4 and normalize. this should be equivalent to what blender does for this situation. should exporter do this, or tell people to limit and normalize themselves?

**Comment by motorsep** [comment] 2018-03-07 17:18
Tbh, I don't understand what the goal here. 75 bones is quite a few bones for mobile apps/games. If artist can utilize all of them, it would be a masterpiece. It's not a question of glTF format but if the artist understands technical limitation and works within those.

Btw, vertex groups split won't work well - if you have 20 bone mesh and you want to split it, you might end up with bunch of meshes and that will increase your drawcalls count. There is no way for exporter to know what to export. And if you want for each mesh chunk to have several vertex groups, how would you even do it ?

I mean, I am not the dev of glTF exporter here, but common sense tells me it's a question of practicality and there is no practical reason in 2018 to split skeletal mesh on export.

**Comment by donmccurdy** [comment] 2018-03-07 17:35
> for the case of >4 weights/vertex, the exporter could chop off everything but largest 4 and normalize. this should be equivalent to what blender does for this situation. should exporter do this, or tell people to limit and normalize themselves?

If you have >4 weights/vertex, the exporter will just write them. For an artist aware that the limitation exists, I don't think there's any advantage to having the exporter arbitrarily chop influences off, versus just using Blender's existing features (and then being able to preview and fix any issues caused by the chopping).

So, my feeling right now is that the exporter should not try to do any guesswork here. But would certainly welcome anyone to test with your preferred engines and share results if there are issues. There might be other use cases for splitting vertex groups to primitives, but at the moment I can't think of anything.

**Comment by ale64bit** [comment] 2018-03-07 19:01
Alright. Well, thanks everyone. I guess in that case it's up to the artist|importer|user to fix this kind of details. Feel free to close it.

**Comment by donmccurdy** [comment] 2019-02-21 05:39
This has been adjusted in the new import/exporter, https://github.com/KhronosGroup/glTF-Blender-IO, and only the highest 4 weights are included by default, unless an option is enabled.

**Closed by donmccurdy** 2019-02-21 05:39 UTC
Labels: enhancement
