### ISSUE TITLE
The exporter exports  wrong vertex color

### ISSUE THREAD

**Issue by Lee-Heisenbug** [KhronosGroup/glTF-Blender-Exporter#256] opened 2018-07-02 07:06 UTC
The vertex color of the model:
![vertex-color](https://user-images.githubusercontent.com/26576701/42149465-c48bb93a-7e08-11e8-8553-35a71f359b61.jpg)

Setting the vertex color of a metallic-roughness material...
![use-color-1-blender](https://user-images.githubusercontent.com/26576701/42149478-cd8e2bb2-7e08-11e8-8a7a-f23f72243ee2.jpg)

Exported result:
![use-color-1-three](https://user-images.githubusercontent.com/26576701/42149594-70290086-7e09-11e8-98d4-89bb9fbf2732.jpg)

Related Softwares:
Blender 2.79
glTF Blender Exporter 1.0
three.js r93

blender file: [vertex-color.zip](https://github.com/KhronosGroup/glTF-Blender-Exporter/files/2154117/vertex-color.zip)

**Comment by donmccurdy** [comment] 2018-12-03 04:18
Going to mark this as a duplicate of https://github.com/KhronosGroup/glTF-Blender-IO/issues/127. I'm not entirely sure it's the same issue, but it may also relate to linear vs gamma interpolation of vertex colors — the vertices themselves all appear to have the right colors, but the faces in between blend differently. That's probably not something we can fix, but it should be minimized as long as we're handling colorspace correctly.

**Closed by donmccurdy** 2018-12-03 04:18 UTC

**Comment by Lee-Heisenbug** [comment] 2018-12-03 05:04
@donmccurdy Thanks for the information.
