### ISSUE TITLE
Preserve Shape Keys with Apply Modifiers on

### ISSUE THREAD

**Issue by feiss** [KhronosGroup/glTF-Blender-Exporter#36] opened 2017-07-10 10:50 UTC
Looking at the feature chart and the code it seems that morph target animations are supported. But I can't manage to export Shape Keys (ie, morph targets in Blender) without animation. Just shape keys, without any keyframe set, and all weights at 0. I checked all options in the "Animation" group of the exporter. Maybe an "Export shapes keys"  in the "Attributes" group would be needed?. Thanks!

**Comment by UX3D-nopper** [comment] 2017-07-10 20:34
Just got back from a business trip. Will check this tomorrow and I mark it as a bug for now.

**Comment by UX3D-nopper** [comment] 2017-07-10 20:46
Hmm, works on my side. Can you please send me the file?

**Comment by feiss** [comment] 2017-07-10 21:29
I've just made a simple test. A plane, with a shape key that raises one vertex. Sorry if I'm doing something wrong..

[planemorph.zip](https://github.com/KhronosGroup/glTF-Blender-Exporter/files/1137137/planemorph.zip)

**Comment by UX3D-nopper** [comment] 2017-07-11 04:51
When I export the file, I do get the follwoing glTF output:

```
{
    "accessors" : [
        {
            "bufferView" : 0, 
            "componentType" : 5121, 
            "count" : 6, 
            "max" : [
                3
            ], 
            "min" : [
                0
            ], 
            "type" : "SCALAR"
        }, 
        {
            "bufferView" : 1, 
            "componentType" : 5126, 
            "count" : 4, 
            "max" : [
                1.0, 
                0.0, 
                1.0
            ], 
            "min" : [
                -1.0, 
                0.0, 
                -1.0
            ], 
            "type" : "VEC3"
        }, 
        {
            "bufferView" : 2, 
            "componentType" : 5126, 
            "count" : 4, 
            "max" : [
                0.0, 
                1.0, 
                -0.0
            ], 
            "min" : [
                0.0, 
                1.0, 
                -0.0
            ], 
            "type" : "VEC3"
        }, 
        {
            "bufferView" : 3, 
            "componentType" : 5126, 
            "count" : 4, 
            "max" : [
                0.0, 
                0.0, 
                0.0
            ], 
            "min" : [
                0.0, 
                0.0, 
                0.0
            ], 
            "type" : "VEC3"
        }, 
        {
            "bufferView" : 4, 
            "componentType" : 5126, 
            "count" : 4, 
            "max" : [
                0.0, 
                0.0, 
                0.0
            ], 
            "min" : [
                0.0, 
                0.0, 
                0.0
            ], 
            "type" : "VEC3"
        }, 
        {
            "bufferView" : 5, 
            "componentType" : 5126, 
            "count" : 4, 
            "max" : [
                0.0, 
                1.4260201454162598, 
                0.0
            ], 
            "min" : [
                0.0, 
                0.0, 
                0.0
            ], 
            "type" : "VEC3"
        }, 
        {
            "bufferView" : 6, 
            "componentType" : 5126, 
            "count" : 4, 
            "max" : [
                -0.3183344900608063, 
                -0.10706871747970581, 
                -0.3183344900608063
            ], 
            "min" : [
                -0.3183344900608063, 
                -0.10706871747970581, 
                -0.3183344900608063
            ], 
            "type" : "VEC3"
        }
    ], 
    "asset" : {
        "generator" : "Khronos Blender glTF 2.0 exporter", 
        "version" : "2.0"
    }, 
    "bufferViews" : [
        {
            "buffer" : 0, 
            "byteLength" : 6, 
            "byteOffset" : 0, 
            "target" : 34963
        }, 
        {
            "buffer" : 0, 
            "byteLength" : 48, 
            "byteOffset" : 8, 
            "target" : 34962
        }, 
        {
            "buffer" : 0, 
            "byteLength" : 48, 
            "byteOffset" : 56, 
            "target" : 34962
        }, 
        {
            "buffer" : 0, 
            "byteLength" : 48, 
            "byteOffset" : 104, 
            "target" : 34962
        }, 
        {
            "buffer" : 0, 
            "byteLength" : 48, 
            "byteOffset" : 152, 
            "target" : 34962
        }, 
        {
            "buffer" : 0, 
            "byteLength" : 48, 
            "byteOffset" : 200, 
            "target" : 34962
        }, 
        {
            "buffer" : 0, 
            "byteLength" : 48, 
            "byteOffset" : 248, 
            "target" : 34962
        }
    ], 
    "buffers" : [
        {
            "byteLength" : 296, 
            "uri" : "planemorph.bin"
        }
    ], 
    "cameras" : [
        {
            "name" : "Camera", 
            "perspective" : {
                "aspectRatio" : 1.703595982340029, 
                "yfov" : 0.5033799409866333, 
                "zfar" : 100.0, 
                "znear" : 0.10000000149011612
            }, 
            "type" : "perspective"
        }
    ], 
    "meshes" : [
        {
            "name" : "Plane", 
            "primitives" : [
                {
                    "attributes" : {
                        "NORMAL" : 2, 
                        "POSITION" : 1
                    }, 
                    "indices" : 0, 
                    "targets" : [
                        {
                            "NORMAL" : 4, 
                            "POSITION" : 3
                        }, 
                        {
                            "NORMAL" : 6, 
                            "POSITION" : 5
                        }
                    ]
                }
            ], 
            "weights" : [
                0.0, 
                0.0
            ]
        }
    ], 
    "nodes" : [
        {
            "camera" : 0, 
            "name" : "Correction_Camera", 
            "rotation" : [
                -0.7071067690849304, 
                -0.0, 
                0.0, 
                0.7071067690849304
            ]
        }, 
        {
            "children" : [
                0
            ], 
            "name" : "Camera", 
            "rotation" : [
                0.48170700669288635, 
                0.3342514932155609, 
                -0.21292175352573395, 
                0.7816000580787659
            ], 
            "scale" : [
                1.0, 
                1.0, 
                0.9999999403953552
            ], 
            "translation" : [
                7.481131553649902, 
                5.34366512298584, 
                6.5076398849487305
            ]
        }, 
        {
            "mesh" : 0, 
            "name" : "Plane"
        }
    ], 
    "scene" : 0, 
    "scenes" : [
        {
            "name" : "Scene", 
            "nodes" : [
                2, 
                1
            ]
        }
    ]
}

```

I double klick and open your file and export. Are u using a Mac Computer? Will try on a Mac later this day.

**Comment by feiss** [comment] 2017-07-11 05:54
oh, that is weird! I must be selecting the wrong export parameters. Could you paste a screenshot of the export panel?

**Comment by feiss** [comment] 2017-07-11 06:26
Oh, I got it! I was exporting with "Apply Modifiers" on. It has sense if you consider shape keys as modifiers of the base mesh, although many would like to apply 'common' modifiers but also preserve and export the shape keys..

**Comment by UX3D-nopper** [comment] 2017-07-11 07:06
At the moment, applying the modifieres is more or less a function call.
I agree, it makes sense to have it somehow selective, where e.g. you apply subdivision but not the morph targets.
I marked it as an enhancement, as it can already achieved manually. Let's collect more cases like this.

**Comment by tauroamp** [comment] 2017-09-08 05:04
Hi!
I have seen this thread and I see that it has to do with some problem that I have to export a basic animation with shape keys.
I have taken the flamingo that someone recently uploaded, and that is exported without problems.
In the same file I inserted Suzanne and I did a basic distortion using only one key.
The result when exporting is that the flamingo is still moving, but the distortion in Suzzane is not observed.
Maybe it's a mistake because of my lack of experience with Blender. I apologize for that.
But do I urgently need to know how shape keys should be prepared to be successfully exported in gltf format?

I attached my blender file.
Thanks in advance!

[flamingo_monkey.zip](https://github.com/KhronosGroup/glTF-Blender-Exporter/files/1286815/flamingo_monkey.zip)

**Comment by UX3D-nopper** [comment] 2017-09-08 05:55
Which glTF loader and viewer are you using?

**Comment by tauroamp** [comment] 2017-09-08 06:05
Hi!
I'm using this: https://gltf-viewer.donmccurdy.com/

**Comment by UX3D-nopper** [comment] 2017-09-08 06:06
Can you please try your model here:
http://sandbox.babylonjs.com/

Also, can you please investigate, if this is an exporter or viewer problem?

**Comment by tauroamp** [comment] 2017-09-08 06:24
On "babylonjs.com" Suzanne is animated, but not flamingo!
But I have an error on my console:
_**BJS - [01:07:58]: Mesh is incompatible with morph targets. Targets and mesh must all have the same vertices count.**_

So, I think the problem is the viewer or my blend scene. 
Could you help me know what the real cause is? (from my blend file attached earler)
My goal is to use the gltf file in Threejs. Can you tell me where I find the best GLTF loader for Threejs?

**Comment by UX3D-nopper** [comment] 2017-09-08 06:28
The strange thing is, that the glTF validator says, that the exported file is okay (the warning comes from the lamp node):
```
[
    {
        "uri": "flamingo_monkey.glb",
        "mimeType": "model/gltf-binary",
        "warnings": {
            "NODE_EMPTY": [
                {
                    "type": "NODE_EMPTY",
                    "path": "#/nodes/3",
                    "message": "Empty node encountered."
                }
            ]
        },
        "resources": [
            {
                "id": "#/buffers/0",
                "mimeType": "application/octet-stream",
                "GLB": true,
                "byteLength": 1046296
            }
        ],
        "info": {
            "version": "2.0",
            "generator": "Khronos Blender glTF 2.0 exporter",
            "hasAnimations": true,
            "hasMaterials": true,
            "hasMorphTargets": true,
            "hasSkins": false,
            "hasTextures": false,
            "hasDefaultScene": true,
            "primitivesCount": 6,
            "maxAttributesUsed": 4
        }
    }
]
```

**Comment by UX3D-nopper** [comment] 2017-09-08 06:32
@donmccurdy Can you please investigate, why the file is not properly loaded/rendered/animated?

**Comment by tauroamp** [comment] 2017-09-08 06:41
Okay, I'll try with several loaders and later I'll send my comments.
Thank you very much for your support.

**Comment by lexaknyazev** [comment] 2017-09-08 11:02
@bghgary 
Gary, could you check [that error output from Babylon](https://github.com/KhronosGroup/glTF-Blender-Exporter/issues/36#issuecomment-328010796)? This asset contains a mesh with multiple morphed primitives.

**Comment by bghgary** [comment] 2017-09-08 17:22
@lexaknyazev A mesh with multiple primitive with morph targets is currently broken in the glTF loader in BabylonJS. I noticed this two weeks ago. I have a backlog item to fix it.

**Comment by donmccurdy** [comment] 2017-09-08 18:58
It looks like the morph targets are intact in three.js, but playback is broken?

![eb80ec45-b59e-4d2a-8dff-325d79635085-55074-0002e6fc0fe604cd](https://user-images.githubusercontent.com/1848368/30226437-d471b114-948a-11e7-9056-1f4ebea1a668.gif)

Also @mrdoob was able to convert a fair number of models with shape keys successfully ([example](https://gltf-viewer.donmccurdy.com/#model=https://raw.githubusercontent.com/mrdoob/rome-gltf/master/files/models/black_soup/alligator.gltf), and [all models](https://mrdoob.github.io/rome-gltf/)). I'm not sure what steps were necessary to do that export.

**Comment by tauroamp** [comment] 2017-09-09 20:18
Hi!
After a day reviewing every detail, I have discovered that Suzanne's animation is not shown because the corresponding "Shape Key" has the "Bezier" value in the type of interpolation.
When I change its value to "Linear", then the animation is reproduced.
I have tested it with other values (not all) and the animation is also achieved.
I really do not know the processing done by the GLTF exporter or its corresponding loader in Threejs, but I think this detail can help optimize it.
Thank you all.

**Comment by McNopper** [comment] 2017-09-09 21:09
Yes, seems the Bezier import/data loading is somehow broken.

Works fine with Babylon JS: 
![grafik](https://user-images.githubusercontent.com/3677213/30243912-bd4b944e-95b3-11e7-96c1-5436bb93d8ac.png)

Sample file with bezier animation:
[01_cs_translate.zip](https://github.com/KhronosGroup/glTF-Blender-Exporter/files/1290104/01_cs_translate.zip)

**Comment by donmccurdy** [comment] 2017-09-10 04:56
There is a problem with the THREE.GLTFLoader handling of cubic spline interpolation. Currently tracking this in https://github.com/aframevr/aframe/issues/3036.

**Comment by donmccurdy** [comment] 2019-02-25 22:15
Fixed upstream in threejs.

**Closed by donmccurdy** 2019-02-25 22:15 UTC
Labels: external bug
