### ISSUE TITLE
Blender exported gltf 2.0 model rotates and deforms unexpectedly during animation playback

### ISSUE THREAD

**Issue by enesser** [KhronosGroup/glTF-Blender-Exporter#103] opened 2017-10-10 06:11 UTC
I have a very simple rig and animation illustrated here:
![animation](https://user-images.githubusercontent.com/5659221/31371360-f38bb980-ad55-11e7-8f3f-9b6879b1ceff.png)

During animation playback, the model rotates unexpectedly and some of the geometry is deformed in a surprising way:
https://gltf-viewer.donmccurdy.com/#model=https://s3-us-west-2.amazonaws.com/s.cdpn.io/168282/rigged-gift.gltf

My Blender file is available here:
https://s3-us-west-2.amazonaws.com/s.cdpn.io/168282/rigged-gift.blend

Export settings:
[x] Export animations
[x] Export within playback range
[x] Keyframes start with 0
[x] Export skinning
[x] Export skinning constraints
[x] Export morphing (no effect on/off; must use skinning)
[x] Export morphing normals (no effect on/off; must use skinning)
[x] Export morphing tangents (no effect on/off; must use skinning)

What am I doing wrong? Is it a bug? Are there good Blender tutorials on exporting animations successfully with gltf? Even if I try to rotate or move a simple default cube, it does not export correctly. 

Thanks so much for your help!

**Comment by UX3D-nopper** [comment] 2017-10-10 08:30
First, the animation data is dublicated. Please delete one of them.
Also, please animate the whole Quaternion and store this data.

Please do the above steps and we can continue investigating this.

**Comment by enesser** [comment] 2017-10-10 09:36
![rig-test](https://user-images.githubusercontent.com/5659221/31379649-842489b8-ad74-11e7-8bfb-83e81f296af1.png)

New Blender file:
https://s3-us-west-2.amazonaws.com/s.cdpn.io/168282/rigged-gift.blend

New gltf:
https://s3-us-west-2.amazonaws.com/s.cdpn.io/168282/rigged-gift-new.gltf

gltf preview:
https://gltf-viewer.donmccurdy.com/#model=https://s3-us-west-2.amazonaws.com/s.cdpn.io/168282/rigged-gift-new.gltf

**Comment by UX3D-nopper** [comment] 2017-10-10 11:21
We used a simplified (removed animations) version of your box, opened it in Blender 2.78c(!), reassinged all weights and exported it again. Then the output is fine.
Maybe it is a bug in Blender and/or because they restructured things.

**Comment by enesser** [comment] 2017-10-10 19:21
@UX3D-nopper Rerigged in 2.78c and had the exact same output. Perhaps the secret was in how you rigged it? Did you use weights? The original version used vertex groups.

**Comment by enesser** [comment] 2017-10-16 06:15
Linking to a simplified rig, structured it identically to Skinned Cylinder demo, XYZ Euler rotation, single action, single bone, rigged in both 2.78c and 2.79, still having the same issue:

Blender:
https://s3-us-west-2.amazonaws.com/s.cdpn.io/168282/rigged-gift-simple.blend

GLTF:
https://s3-us-west-2.amazonaws.com/s.cdpn.io/168282/rigged-gift-simple.gltf

All children of the armature rotate for some reason. Tried separating out the model into separate meshes and de-parented them from the armature; they don't render at all in that case even though they're selected/or I exported all. 

Thanks so much for anyone looking into this!

**Comment by UX3D-nopper** [comment] 2017-10-16 06:46
NLA tracks are currently not supported by the exporter, as the NLA Blender implementation itself is buggy.
Can you please modify your example, that you are not using any NLA tracks?
If the bug still occurs, we can help u on this.

**Comment by enesser** [comment] 2017-10-16 06:55
Sure. Updated at the link:
https://s3-us-west-2.amazonaws.com/s.cdpn.io/168282/rigged-gift-simple.blend

Only reason I included NLA tracks is because they were included here and I tried copying the setup exactly:
https://github.com/KhronosGroup/glTF-Blender-Exporter/blob/master/scenes/03_skinned_cylinder.blend

**Comment by UX3D-nopper** [comment] 2017-10-16 07:05
During export, please select: 'Force Sample Animations'
This is required because of the euler rotation.

Attached is a screenshot generated from our UX3D Engine:
![screenshot_0](https://user-images.githubusercontent.com/27856744/31598956-a73036e2-b250-11e7-9cbd-92873aeebf55.png)
The animation etc. works fine.

However, I tried out the glTF file in other glTF viewers and they produce garbage.
Please raise an issue for the viewer you have problmes with.

**Comment by enesser** [comment] 2017-10-16 07:14
Okay, still having an issue with A-Frame v0.7.0 which is ThreeJS r87. Do you think there is an issue with the ThreeJS gltf importer in A-Frame?

How do I test with the UX3D engine viewer? 

Thanks!

**Comment by UX3D-nopper** [comment] 2017-10-16 07:17
Unfortunately, the UX3D Engine and its viewer is not public yet.
Yes, I assume the problem is with three.js. As Babylon JS also does have problems, possibly it is the glTF importer or other code both engines do share.
I close this issue for now, as the export works fine.

**Closed by UX3D-nopper** 2017-10-16 07:17 UTC
Labels: help wanted, question
