### ISSUE TITLE
 add KHR_texture_transform support?

### ISSUE THREAD

**Issue by sonygod** [KhronosGroup/glTF-Blender-Exporter#226] opened 2018-05-24 06:37 UTC
add KHR_texture_transform support?

**Comment by donmccurdy** [comment] 2018-05-24 16:37
We can support this without any new nodes — there are native settings for offset/scale in Blender Render, and offset/scale/rotation in cycles:

https://blender.stackexchange.com/questions/5608/rotate-object-texture

![screen shot 2018-05-24 at 9 36 08 am](https://user-images.githubusercontent.com/1848368/40499181-03ec375e-5f36-11e8-98bc-ef831f3a2817.png)

![screen shot 2018-05-24 at 9 35 56 am](https://user-images.githubusercontent.com/1848368/40499183-06340f32-5f36-11e8-9551-dde7289c0a8f.png)

`z` values of offset/scale and `x/y` coordinates of rotation would be ignored.

**Comment by donmccurdy** [comment] 2018-05-24 16:49
> But we really need to work on making things more friendly towards normal Blender-loving Blender users who just happen to be looking for a 3D export format like glTF. Meaning, we should make things like this work with native Blender options and settings, without asking indigenous Blender users to import our custom-built node graphs into their own Blender projects.

I agree with all of this, and in particular would consider Principled BSDF support to be quite important. But I am worried that even if we don't require any custom nodes, we'll still need to give opinionated examples of how to construct the node graph — parsing and exporting an arbitrary node graph seems extremely difficult, even when the graph can be fully represented in glTF. For example, I can find no way to parse a group of nodes that output a texture, except to get the image reference from the Image Texture node and ignore any operations performed by other nodes on that texture. 😕

**Comment by McNopper** [comment] 2018-05-24 17:14
I do have code, which is parsing the whole tree plus it is generating GLSL code. If we can agree on a extension, the integration is some days work.

**Comment by donmccurdy** [comment] 2018-05-24 18:48
I think the essential goal is to support creation of PBR materials in "native Blender" ways, specifically the Principled BSDF node. 

Support for parsing arbitrary (e.g. non-PBR) node trees into `KHR_techniques_webgl` would also be good to explore, but it is of secondary importance in my opinion.

**Comment by donmccurdy** [comment] 2018-05-24 20:08
It's worth noting that Blender 2.8 allows use of Principled BSDF materials in the sidebar, without nodes:

| | |
|--|--|
| <img width="586" alt="screen shot 2018-05-24 at 1 04 47 pm" src="https://user-images.githubusercontent.com/1848368/40511036-62d56cb4-5f53-11e8-8f97-766cd61d1cf7.png"> | <img width="584" alt="screen shot 2018-05-24 at 1 05 06 pm" src="https://user-images.githubusercontent.com/1848368/40511047-689dcb5a-5f53-11e8-81c4-7b79b1a3af64.png"> |

Unfortunately it's all still unstable enough that Blender crashes if I click anything in that menu. 😅

**Comment by emackey** [comment] 2018-05-24 20:15
Yep.  Blender 2.79 can do that too, it's stable there.  I've been using it with our custom glTF node.

**Comment by donmccurdy** [comment] 2018-05-24 21:33
Oh, I didn't realize that! It expands quite nicely to allow addition of texture transforms and selecting a UV set:

![screen shot 2018-05-24 at 2 32 20 pm](https://user-images.githubusercontent.com/1848368/40514795-657e37aa-5f5f-11e8-9ddc-488766b78d4f.png)

So at least if we have to be opinionated about node graph structure, we can choose the same opinions as Blender generates. 😅

**Comment by emackey** [comment] 2018-05-24 22:05
Ah, OK.  Yeah I'd be fine in the short term saying that you just pick those vector options here and it encodes to the transform extension.  That would probably continue to work or be made to work again later when we find an image node attached to the Principled node, as the same vector mappings apply on the image node the same way.

**Comment by sonygod** [comment] 2018-05-25 02:12
@emackey 
sorry for late, the workflow  is  unity to blender or blender to unity  .
current we want  these two engine work together .
unity call blender  bake or render result to unity ,also include material information from unity to blender or blender to unity . so. add KHR_texture_transform support seem necessity 

I compare many other format ,but it's find gtlf2 is the best at current time.

**Comment by donmccurdy** [comment] 2018-12-02 07:44
Closing as duplicate of https://github.com/KhronosGroup/glTF-Blender-IO/issues/113.

**Closed by donmccurdy** 2018-12-02 07:44 UTC
Labels: enhancement
