### ISSUE TITLE
User count of some meshes increase when exporting scene to gltf format

### ISSUE THREAD

**Issue by Cyp** [KhronosGroup/glTF-Blender-Exporter#306] opened 2018-09-26 12:15 UTC
When exporting the scene to .gltf format, the user count of an arbitrary (recently edited?) set of meshes goes up. If exporting 5 times, the user count of the meshes go up by 5.

If saving and reverting (File/Revert), then the user count goes back to what it should be, until exporting again.

I'm not sure how it decides which particular meshes to increase the user count of.

I originally reported [there](https://developer.blender.org/T56924), but in retrospect should probably have reported here instead.

**Comment by donmccurdy** [comment] 2018-12-12 05:42
As far as I can tell this problem is resolved in the new project and Blender 2.8, https://github.com/KhronosGroup/glTF-Blender-IO. The user count is no longer shown in Blender's UI, but you can access it through the Python API.

If the issue is recurring for you, steps or files to reproduce the problem would be helpful. Thanks!

**Closed by donmccurdy** 2018-12-12 05:42 UTC
